version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smartbid
      MYSQL_DATABASE: smartbid
      MYSQL_USER: smartbid
      MYSQL_PASSWORD: smartbid
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:8080"
volumes:
  db_data: