version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smartbid
      MYSQL_DATABASE: smartbid
      MYSQL_USER: smartbid
      MYSQL_PASSWORD: smartbid
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web-server:
    container_name: "wildfly-marvin2"
    image: teste-wild
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=DLeY&S5uw6Z2VU!@
    ports:
      - "8082:8080"
      - "9992:9990"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9090:8080"

volumes:
  db_data:
