version: '3'
services:
  app:
    container_name: "smartbid"
    image: "smartbid-wildfly"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=adminPassword
      - DB_NAME=smartbid
      - DB_USER=smartbid
      - DB_PASS=smartbid
      - DB_URI=db:3306
    depends_on:
      - db
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console
      - "8787:8787" # debug port
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smartbid
      MYSQL_DATABASE: smartbid
      MYSQL_USER: smartbid
      MYSQL_PASSWORD: smartbid
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9090:8080"

volumes:
  db_data:
